export default {
	ADD_ITEM: 'ADD_ITEM',
	REMOVE_ITEM: 'REMOVE_ITEM',
	SET_BASE_INGREDIENT: 'SET_BASE_INGREDIENT',
	SET_FINAL_RECIPE: 'SET_FINAL_RECIPE',
	GET_RECIPES: 'GET_RECIPES',
	GET_RECIPES_SUCCESS: 'GET_RECIPES_SUCCESS',
	GET_AVAILABLE_INGREDIENTS: 'GET_AVAILABLE_INGREDIENTS',
	GET_AVAILABLE_INGREDIENTS_SUCCESS: 'GET_AVAILABLE_INGREDIENTS_SUCCESS'
}